version: "3.8"
services:
  web:
    image: ruby:3.0
    container_name: web
    working_dir: /usr/src/app/
    command:
      - "/bin/sh"
      - "-c"
      - "bundle install && exec bin/rails server --binding 0.0.0.0 --port 3000"
    environment:
      DATABASE_URL: postgres://web:password@pg/app_development
    depends_on:
      - pg
    volumes:
      - .:/usr/src/app/
      - gem_data:/usr/local/bundle/
    ports:
      - 3000:3000
  pg:
    image: postgres:14.1
    container_name: pg
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: web
      POSTGRES_DB: app_development
    volumes:
      - db_data:/var/lib/postgresql/data/
volumes:
  gem_data:
  db_data:
